name: Build .NET Project

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código do repositório
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore
        working-directory: ./github4women

      - name: Build do projeto
        run: dotnet build --configuration Release
        working-directory: ./github4women

      - name: Teste personalizado - Listar arquivos do projeto
        run: ls -R
        working-directory: ./github4women
